name: shared
description: Shared models, utilities, and data structures for Spot Booker applications
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter: 
    sdk: flutter
  cloud_firestore: ^5.4.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: false