// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWiVpEKjf5uxE76z78y_ch-Y_qXoixi8Q',
    appId: '1:1074093755166:web:c8a49c79c0b6b3318b170f',
    messagingSenderId: '1074093755166',
    projectId: 'spot-booker-v2',
    authDomain: 'spot-booker-v2.firebaseapp.com',
    storageBucket: 'spot-booker-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWiVpEKjf5uxE76z78y_ch-Y_qXoixi8Q',
    appId: '1:1074093755166:android:a1b49c79c0b6b3318b170f',
    messagingSenderId: '1074093755166',
    projectId: 'spot-booker-v2',
    authDomain: 'spot-booker-v2.firebaseapp.com',
    storageBucket: 'spot-booker-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWiVpEKjf5uxE76z78y_ch-Y_qXoixi8Q',
    appId: '1:1074093755166:ios:b2c49c79c0b6b3318b170f',
    messagingSenderId: '1074093755166',
    projectId: 'spot-booker-v2',
    authDomain: 'spot-booker-v2.firebaseapp.com',
    storageBucket: 'spot-booker-v2.firebasestorage.app',
    iosBundleId: 'com.example.clientApp',
  );
}
