name: panel
description: Spot Booker Admin Panel - Flutter Web Application
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  
  # Routing & State
  go_router: ^14.3.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  
  # Utilities
  intl: ^0.19.0
  
  # Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Shared models
  shared:
    path: ../../packages/shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true